project:
  type: website
  output-dir: docs

website:
  title: "test_shiny_python"
  navbar:
    left:
      - href: triz_39_45/index.html
        text: TRIZ      
      - href: test.qmd
        text: TRIZ-test         
      - href: 9w.qmd
        text: 9w-test         
      - href: 5whys.qmd
        text: 5whys-test                   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



